name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  prepare-env:
    runs-on: [self-hosted]
    steps:
      - name: Create secrets files
        run: |
          mkdir -p ${{vars.DEPLOY_PATH}}/${{ github.event.repository.name }}
          echo "COUCHDB_USER=${{ secrets.COUCHDB_USER }}" > ${{vars.DEPLOY_PATH}}/${{ github.event.repository.name }}/.env 
          echo "COUCHDB_PASSWORD=${{ secrets.COUCHDB_PASSWORD }}" >> ${{vars.DEPLOY_PATH}}/${{ github.event.repository.name }}/.env 
  call-deploy:
    needs: [prepare-env]
    uses: leoserverteam/DevOpsTemplates/.github/workflows/onlycompose.yml@main
    with:
      project_name: "${{ github.event.repository.name }}"
      extra_files: "couchdb" 

  call-nginx:
    needs: [call-deploy]
    uses: leoserverteam/DevOpsTemplates/.github/workflows/deploynginx.yml@main
